<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<!-- ОСНОВНОЙ пакет EF Core -->
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />

		<!-- Инструменты для команд и миграций -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.6">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.6" />

		<!-- Поставщик для PostgreSQL (ОБЯЗАТЕЛЬНО укажите версию!) -->
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
	</ItemGroup>

</Project>